apiVersion: eaf.dev/v1
kind: JenkinsCaller
metadata:
  name: my-caller      
spec:
  appid: "APP12"
  jobname: devops/caller_test
  jobparams:
    msg: "ArgoCD should trigger a build when this is pushed"
    msg2: "If It doesn't work, we'll try again"